<?xml version="1.0"?>
<package format="2">
  <name>teleop_twist_keyboard_for_azerty</name>
  <version>1.0.0</version>
  <description>
    A modified version of the teleoperation node optimized for AZERTY keyboards, converting keyboard commands to Twist messages.
  </description>

  <maintainer email="axelniato@gmail.com">Axel Niato</maintainer>

  <license>BSD License 2.0</license>

  <author email="namniart@gmail.com">Austin Hendrix</author>
  <author>Graylin Trevor Jay</author>

  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
